### ISSUE TITLE
Proposal: File extension should at least allow for .cfn.yaml/json

### ISSUE THREAD

**Issue by timzuiddam** [keyboardDrummer/cloudformation-ide-tooling#9]
AWS uses CF as the abbreviation for CloudFront and CFN for CloudFormation, so it would make sense to at least allow for that extension as well. How do you feel about adding these (.cfn.yaml & .cfn.json) as secondary (/primary) file extensions for the VSCode plugin?

An alternative would be to give people the freedom to change the extensions, but I'm not sure if that's possible.

**Comment by keyboardDrummer** [comment]
Hey, thanks for the feedback.

Freedom to change the extensions isn't possible since the file extensions that a VSCode extension introduces for a particular language are defined statically and they can't be adjusted dynamically.

However, I've added the extensions you propose as alternatives for the existing extensions, and updated the README to make the one you propose the default ones.

**Comment by timzuiddam** [comment]
Awesome, thanks! My current projects use those file extensions already, so now the plugin will see a lot more use. If I have some feedback, will let you know.

Btw, apart from file extensions, aren't there other ways to activate it on a file? Like selecting it as a language or just trigger on .json & .yaml and only really activate on a pattern, like the first line always contains 'AWSTemplateFormatVersion'.

**Comment by keyboardDrummer** [comment]
> Btw, apart from file extensions, aren't there other ways to activate it on a file? Like selecting it as a language

You can select it as a language on an arbitrary file. From the README: "You can set the language mode for a file to "CloudFormation JSON" or "CloudFormation YAML" using the language picker in the bottom right."

>  or just trigger on .json & .yaml and only really activate on a pattern, like the first line always contains 'AWSTemplateFormatVersion'.

Sadly that doesn't seem possible with the VSCode API (see [here](https://code.visualstudio.com/api/references/vscode-api#DocumentSelector) for some documentation), I would've liked to be able to do that though..

**Comment by timzuiddam** [comment]
@keyboardDrummer Ah, missed that somehow as I read the README. Thanks again.

Curious how other extensions handle it, like for instance the cfn-lint one (https://marketplace.visualstudio.com/items?itemName=kddejong.vscode-cfn-lint)

**Comment by keyboardDrummer** [comment]
Well you can start a language server and run it on any `.json` or `.yaml` file, and then simply let the language server not return any results if the file isn't a CloudFormation file. That's just a bit heavy handed.. It is what cfn-lint does though. 

You can see it here for example: https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/blob/master/server/src/server.ts#L157

**Comment by timzuiddam** [comment]
@keyboardDrummer Ah, thanks for this.
Actually feels a bit disappointing that cfn-lint resorts to this and that there is no other way.

**Comment by keyboardDrummer** [comment]
Em, yeah.. it's a little annoying but honestly why not make the file extensions more specific?

I feel that once you require analysing the file to determine whether you want to analyse the file, you're in a deep hole ^^

A quick fix here would be to allow document selectors to specify a regex on the content of the file to determine whether to match on it, but then you're limited to detecting what you can with regex which is kind of arbitrary, so I don't blame VSCode for working the way it does.
